---

- name: Install Redis
  apt:
    name: redis-server

- name: Enable memory overcommit
  sysctl:
    name: vm.overcommit_memory
    value: 1
    reload: yes

- name: Ensure Redis is running and enabled on boot.
  service:
    name: redis-server
    state: started
    enabled: true
